import { getValue } from "./core";
import type { ThemeConfig } from "./types";

export enum ColorfulTheme {
  Background = "background",
  Foreground = "foreground",
  Surface = "surface",
  OnSurface = "on-surface",
  SurfaceInverse = "surface-inverse",
  OnSurfaceInverse = "on-surface-inverse",
  Container = "container",
  OnContainer = "on-container",
  Muted = "muted",
  OnMuted = "on-muted",
  Primary = "primary",
  OnPrimary = "on-primary",
  PrimarySurface = "primary-surface",
  OnPrimarySurface = "on-primary-surface",
  PrimaryContainer = "primary-container",
  OnPrimaryContainer = "on-primary-container",
  PrimaryOutline = "primary-outline",
  PrimaryDim = "primary-dim",
  OnPrimaryDim = "on-primary-dim",
  Secondary = "secondary",
  OnSecondary = "on-secondary",
  SecondarySurface = "secondary-surface",
  OnSecondarySurface = "on-secondary-surface",
  SecondaryContainer = "secondary-container",
  OnSecondaryContainer = "on-secondary-container",
  SecondaryOutline = "secondary-outline",
  SecondaryDim = "secondary-dim",
  OnSecondaryDim = "on-secondary-dim",
  Tertiary = "tertiary",
  OnTertiary = "on-tertiary",
  TertiarySurface = "tertiary-surface",
  OnTertiarySurface = "on-tertiary-surface",
  TertiaryContainer = "tertiary-container",
  OnTertiaryContainer = "on-tertiary-container",
  TertiaryOutline = "tertiary-outline",
  TertiaryDim = "tertiary-dim",
  OnTertiaryDim = "on-tertiary-dim",
  Error = "error",
  OnError = "on-error",
  ErrorSurface = "error-surface",
  OnTErrorSurface = "on-error-surface",
  ErrorContainer = "error-container",
  OnErrorContainer = "on-error-container",
  ErrorOutline = "error-outline",
  ErrorDim = "error-dim",
  OnErrorDim = "on-error-dim",
  Shadow = "shadow",
  Scrim = "scrim",
  Dim = "dim",
  OnDim = "on-dim",
  Outline = "outline",
  OutlineVariant = "outline-variant",
}

export type ColorfulThemeKeys = `${ColorfulTheme}`;

export const COLORFUL_THEME: ThemeConfig<ColorfulThemeKeys>[] = [
  {
    key: "background",
    light: getValue("gray", 0),
    dark: getValue("gray", 950),
  },
  {
    key: "foreground",
    light: getValue("gray", 950),
    dark: getValue("gray", 950, { useContrast: true }),
  },
  {
    key: "surface",
    light: getValue("neutral", 50),
    dark: getValue("neutral", 900),
  },
  {
    key: "on-surface",
    light: getValue("neutral", 50, { useContrast: true }),
    dark: getValue("neutral", 900, { useContrast: true }),
  },
  {
    key: "surface-inverse",
    light: getValue("neutral", 900),
    dark: getValue("neutral", 100),
  },
  {
    key: "on-surface-inverse",
    light: getValue("neutral", 900, { useContrast: true }),
    dark: getValue("neutral", 100, { useContrast: true }),
  },
  {
    key: "container",
    light: getValue("neutral", 100),
    dark: getValue("neutral", 800),
  },
  {
    key: "on-container",
    light: getValue("neutral", 100, { useContrast: true }),
    dark: getValue("neutral", 800, { useContrast: true }),
  },
  {
    key: "muted",
    light: getValue("neutral", 500),
    dark: getValue("neutral", 500),
  },
  {
    key: "on-muted",
    light: getValue("neutral", 500, { useContrast: true }),
    dark: getValue("neutral", 500, { useContrast: true }),
  },
  {
    key: "primary",
    light: getValue("primary", 500),
    dark: getValue("primary", 500),
  },
  {
    key: "on-primary",
    light: getValue("primary", 500, { useContrast: true }),
    dark: getValue("primary", 500, { useContrast: true }),
  },
  {
    key: "primary-surface",
    light: getValue("primary", 50),
    dark: getValue("primary", 900),
  },
  {
    key: "on-primary-surface",
    light: getValue("primary", 50, { useContrast: true }),
    dark: getValue("primary", 900, { useContrast: true }),
  },
  {
    key: "primary-container",
    light: getValue("primary", 100),
    dark: getValue("primary", 800),
  },
  {
    key: "on-primary-container",
    light: getValue("primary", 100, { useContrast: true }),
    dark: getValue("primary", 800, { useContrast: true }),
  },
  {
    key: "primary-outline",
    light: getValue("primary", 300),
    dark: getValue("primary", 700),
  },
  {
    key: "primary-dim",
    light: getValue("primary", 700),
    dark: getValue("primary", 300),
  },
  {
    key: "on-primary-dim",
    light: getValue("primary", 700, { useContrast: true }),
    dark: getValue("primary", 300, { useContrast: true }),
  },
  {
    key: "secondary",
    light: getValue("secondary", 500),
    dark: getValue("secondary", 500),
  },
  {
    key: "on-secondary",
    light: getValue("secondary", 500, { useContrast: true }),
    dark: getValue("secondary", 500, { useContrast: true }),
  },
  {
    key: "secondary-surface",
    light: getValue("secondary", 50),
    dark: getValue("secondary", 900),
  },
  {
    key: "on-secondary-surface",
    light: getValue("secondary", 50, { useContrast: true }),
    dark: getValue("secondary", 900, { useContrast: true }),
  },
  {
    key: "secondary-container",
    light: getValue("secondary", 100),
    dark: getValue("secondary", 800),
  },
  {
    key: "on-secondary-container",
    light: getValue("secondary", 100, { useContrast: true }),
    dark: getValue("secondary", 800, { useContrast: true }),
  },
  {
    key: "secondary-outline",
    light: getValue("secondary", 300),
    dark: getValue("secondary", 700),
  },
  {
    key: "secondary-dim",
    light: getValue("secondary", 700),
    dark: getValue("secondary", 300),
  },
  {
    key: "on-secondary-dim",
    light: getValue("secondary", 700, { useContrast: true }),
    dark: getValue("secondary", 300, { useContrast: true }),
  },
  {
    key: "tertiary",
    light: getValue("tertiary", 500),
    dark: getValue("tertiary", 500),
  },
  {
    key: "on-tertiary",
    light: getValue("tertiary", 500, { useContrast: true }),
    dark: getValue("tertiary", 500, { useContrast: true }),
  },
  {
    key: "tertiary-surface",
    light: getValue("tertiary", 50),
    dark: getValue("tertiary", 900),
  },
  {
    key: "on-tertiary-surface",
    light: getValue("tertiary", 50, { useContrast: true }),
    dark: getValue("tertiary", 900, { useContrast: true }),
  },
  {
    key: "tertiary-container",
    light: getValue("tertiary", 100),
    dark: getValue("tertiary", 800),
  },
  {
    key: "on-tertiary-container",
    light: getValue("tertiary", 100, { useContrast: true }),
    dark: getValue("tertiary", 800, { useContrast: true }),
  },
  {
    key: "tertiary-outline",
    light: getValue("tertiary", 300),
    dark: getValue("tertiary", 700),
  },
  {
    key: "tertiary-dim",
    light: getValue("tertiary", 700),
    dark: getValue("tertiary", 300),
  },
  {
    key: "on-tertiary-dim",
    light: getValue("tertiary", 700, { useContrast: true }),
    dark: getValue("tertiary", 300, { useContrast: true }),
  },
  {
    key: "error",
    light: getValue("error", 500),
    dark: getValue("error", 500),
  },
  {
    key: "on-error",
    light: getValue("tertiary", 500, { useContrast: true }),
    dark: getValue("error", 500, { useContrast: true }),
  },
  {
    key: "error-surface",
    light: getValue("error", 50),
    dark: getValue("error", 900),
  },
  {
    key: "on-error-surface",
    light: getValue("error", 50, { useContrast: true }),
    dark: getValue("error", 900, { useContrast: true }),
  },
  {
    key: "error-container",
    light: getValue("error", 100),
    dark: getValue("error", 800),
  },
  {
    key: "on-error-container",
    light: getValue("error", 100, { useContrast: true }),
    dark: getValue("error", 800, { useContrast: true }),
  },
  {
    key: "error-outline",
    light: getValue("error", 300),
    dark: getValue("error", 700),
  },
  {
    key: "error-dim",
    light: getValue("error", 700),
    dark: getValue("error", 300),
  },
  {
    key: "on-error-dim",
    light: getValue("error", 700, { useContrast: true }),
    dark: getValue("error", 300, { useContrast: true }),
  },
  {
    key: "shadow",
    light: getValue("gray", 950),
    dark: getValue("gray", 950),
  },
  {
    key: "scrim",
    light: getValue("gray", 950),
    dark: getValue("gray", 950),
  },
  {
    key: "dim",
    light: getValue("gray", 700),
    dark: getValue("gray", 300),
  },
  {
    key: "on-dim",
    light: getValue("gray", 700, { useContrast: true }),
    dark: getValue("gray", 300, { useContrast: true }),
  },
  {
    key: "outline",
    light: getValue("neutral", 300),
    dark: getValue("neutral", 700),
  },
  {
    key: "outline-variant",
    light: getValue("gray", 400),
    dark: getValue("gray", 600),
  },
];
